services:
  app:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: lms_app
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}

  db:
    image: mysql:8.0
    container_name: lcr_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: library
      MYSQL_USER: library_user
      MYSQL_PASSWORD: lib_pass
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lcr_pma
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db

volumes:
  db_data:
